name: Tag

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  tag:
    permissions:
      contents: write
      pull-requests: write
    uses: theholocron/.github/.github/workflows/tag.yml@main
    secrets: inherit
